### ISSUE TITLE
Snapshot is generated, but its submission fails

### ISSUE THREAD

**Issue by sadovnikov** [advanced-security/maven-dependency-submission-action#42]
We are trying to use `advanced-security/maven-dependency-submission-action@v3` with GitHub Enterprise Server `3.8.5 56a917b`.  So far, on two out of two different repositories, the action fails to submit the generated snapshot. Please, see the screenshots and logs below.

Anything we can do on our side to resolve this problem?

```
    - name: Maven Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v3
      if: inputs.build-tool == 'mvn' && steps.setup.outputs.build-config
      with:
        directory: ${{ github.workspace }}
```

![image](https://github.com/advanced-security/maven-dependency-submission-action/assets/4749332/c9da6646-2981-41a7-b0ed-cf9fdc1dccf1)
...
![image](https://github.com/advanced-security/maven-dependency-submission-action/assets/4749332/75802729-eb93-4a81-9ff4-f13fbf929834)

```
            "name": "docker-playground",
            "file": {
                "source_location": "pom.xml"
            }
        }
    }
}
2023-07-07T09:10:25.8804368Z ##[error]Cannot read properties of null (reading 'toString')
2023-07-07T09:10:25.9290668Z ##[error]TypeError: Cannot read properties of null (reading 'toString')
    at /runner/_work/_actions/advanced-security/maven-dependency-submission-action/v3/webpack:/maven-dependency-tree-submission/node_modules/@github/dependency-submission-toolkit/dist/index.js:506:1
    at Generator.next (<anonymous>)
    at fulfilled (/runner/_work/_actions/advanced-security/maven-dependency-submission-action/v3/webpack:/maven-dependency-tree-submission/node_modules/@github/dependency-submission-toolkit/dist/index.js:395:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-07-07T09:10:25.9313110Z 
2023-07-07T09:10:25.9314090Z /runner/_work/_actions/advanced-security/maven-dependency-submission-action/v3/webpack:/maven-dependency-tree-submission/node_modules/@github/dependency-submission-toolkit/dist/index.js:395
2023-07-07T09:10:25.9314308Z         function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
2023-07-07T09:10:25.9314407Z ^
2023-07-07T09:10:25.9314761Z Error: Failed to submit snapshot: TypeError: Cannot read properties of null (reading 'toString')
2023-07-07T09:10:25.9315357Z     at /runner/_work/_actions/advanced-security/maven-dependency-submission-action/v3/webpack:/maven-dependency-tree-submission/node_modules/@github/dependency-submission-toolkit/dist/index.js:520:1
2023-07-07T09:10:25.9315488Z     at Generator.next (<anonymous>)
2023-07-07T09:10:25.9316120Z     at fulfilled (/runner/_work/_actions/advanced-security/maven-dependency-submission-action/v3/webpack:/maven-dependency-tree-submission/node_modules/@github/dependency-submission-toolkit/dist/index.js:395:1)
2023-07-07T09:10:25.9316657Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-07-07T09:10:25.9499359Z Post job cleanup.
```

**Comment by Gby56** [comment]
Also similar problem on our end, I think forgetting to put the permission for contents: write is failing silently the submission

**Comment by peter-murray** [comment]
@sadovnikov Can you possibly share the workflow file that you have that is able to generate this and whether or not you have set any limited actions permissions on the organizations or repositories?
