### ISSUE TITLE
Submission fail with CLI

### ISSUE THREAD

**Issue by balza** [advanced-security/maven-dependency-submission-action#58]
Hello,
I've integrated https://github.com/advanced-security/maven-dependency-submission-action/releases/tag/v3.0.3 CLI in Jenkins.
While scanning a complex maven pom.xml file I get this error

```
::error::Cannot read properties of null (reading 'toString')
::error::TypeError: Cannot read properties of null (reading 'toString')%0A    at /snapshot/maven-dependency-submission-action/node_modules/@github/dependency-submission-toolkit/webpack:/@github/dependency-submission-toolkit/dist/snapshot.js:139:1%0A    at Generator.next (<anonymous>)%0A    at fulfilled (/snapshot/maven-dependency-submission-action/node_modules/@github/dependency-submission-toolkit/webpack:/@github/dependency-submission-toolkit/dist/snapshot.js:28:1)%0A    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Failed to submit the dependency snapshot, check logs for more details, Error: Failed to submit snapshot: TypeError: Cannot read properties of null (reading 'toString')
Error: Failed to submit snapshot: TypeError: Cannot read properties of null (reading 'toString')
    at /snapshot/maven-dependency-submission-action/node_modules/@github/dependency-submission-toolkit/webpack:/@github/dependency-submission-toolkit/dist/snapshot.js:153:1
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/maven-dependency-submission-action/node_modules/@github/dependency-submission-toolkit/webpack:/@github/dependency-submission-toolkit/dist/snapshot.js:28:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Failed to submit snapshot: TypeError: Cannot read properties of null (reading 'toString')
```
with simpler pom.xml the problem does not arise

```
::notice::Snapshot successfully created at 2023-12-15T14:33:19.596Z
completed.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  6344    0  6086  100   258  18149    769 --:--:-- --:--:-- --:--:-- 18937
+ [[ NUMBER_BLOCKING_VULNERABILITIES -ne 0 ]]
+ echo 'The following 17 dangerous vulnerability/ies was/were found: '
```

**Comment by peter-murray** [comment]
Any chance you can share the POM file?

**Comment by peter-murray** [comment]
Looking at the issue stack traces, the dependency toolkit library that is being used to submit the snapshot is erroring here:

```
core.notice('Snapshot successfully created at ' + response.data.created_at.toString());
```

That would seem to indicate that the submission result data is not right, the API https://docs.github.com/en/rest/dependency-graph/dependency-submission?apiVersion=2022-11-28#create-a-snapshot-of-dependencies-for-a-repository here should always return the `created_at` if it was successful.

Was there any additional log data from Jenkins when it failed?

**Comment by peter-murray** [comment]
Looking upstream into the library, it has been fixed already in version `2.0.0`, so I will have to update to that version of the library to remedy this.

**Comment by balza** [comment]
thanks @peter-murray. At the moment I can't reproduce the error, I try updating the library to latest version.

**Comment by peter-murray** [comment]
This has been fixed in the latest `v4` versions, the issue came from the underlying library here that was upgraded to have improved error handling and was adopted in the `v4` versions of the action.
